#!/usr/bin/env bash

#########################################
#   Programa CGI para rodar localmente  #
#########################################

cat <<FIM

<html>
    <head>
        <meta charset=UTF-8>
        <style>
            body {
                background-color: #2c2c2c;
                color: #efefef;
                font-family: "Lucida Console", monospace;
                font-size: 16px;
            }
            h1 {
                color: #fedc33;
                font-size: 30px;
            }
            h2 {
                color: #fedc33;
                font-size: 20px;
            }
            p {color: #efefef;}
            
        </style>
    </head>
    <body>
    
        <h2>Informações da máquina</h2>
        
        <pre>$(uname -a)</pre>
        
        <h2>Uptime da máquina</h2>
        
        <pre>$(uptime)</pre>
        
        <h2>Variáveis de ambiente do CGI</h2>
        
        <pre>$(env)</pre>
    
    </body>
</html>
FIM
